

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  goapi:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      EMAIL_USERNAME: sungjinta@gmail.com
      EMAIL_PASSWORD: aqio nbmf kdwv wkeu
    depends_on:
      - postgres
    volumes:
      - uploads_data:/root/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  
